# Generated by Django 6.0.3 on 2026-03-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='template_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
