# Generated by Django 6.0.3 on 2026-03-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_broadcast_template_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image_url',
            field=models.TextField(blank=True),
        ),
    ]
