# Generated by Django 6.0.3 on 2026-03-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0005_discountcode_discountusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_interaction',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
